### ISSUE TITLE
 libtinfo.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by syguan96** [taichi-dev/taichi_blend#10]
My system is ubuntu18 and the blender version is 2.93.

When I run `import taichi as ti`, an error arised:
```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/user/.config/blender/2.93/scripts/addons/Taichi-Blend/bundle-packages/taichi/__init__.py", line 1, in <module>
    from taichi.core import *
  File "/home/user/.config/blender/2.93/scripts/addons/Taichi-Blend/bundle-packages/taichi/core/__init__.py", line 1, in <module>
    from taichi.core.logging import *
  File "/home/user/.config/blender/2.93/scripts/addons/Taichi-Blend/bundle-packages/taichi/core/logging.py", line 4, in <module>
    from taichi.core import util
  File "/home/user/.config/blender/2.93/scripts/addons/Taichi-Blend/bundle-packages/taichi/core/util.py", line 171, in <module>
    import_ti_core()
  File "/home/user/.config/blender/2.93/scripts/addons/Taichi-Blend/bundle-packages/taichi/core/util.py", line 48, in import_ti_core
    raise e from None
  File "/home/user/.config/blender/2.93/scripts/addons/Taichi-Blend/bundle-packages/taichi/core/util.py", line 36, in import_ti_core
    import taichi_core as core
ImportError: libtinfo.so.6: cannot open shared object file: No such file or directory
Consider installing libtinfo5: sudo apt-get install libtinfo5
```

Could you help me?

**Comment by shankarsivarajan** [comment]
Are you using the correct version? Blender 2.93 uses Python 3.9.

**Comment by archibate** [comment]
Try `sudo apt install libtinfo`? This seems to be a taichi bug only exists in 3.9..











无法顺畅的大口呼吸，是活着的最好证明

---Original---
From: "Shankar ***@***.***&gt;
Date: Mon, Jul 5, 2021 07:57 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [taichi-dev/taichi_blend]  libtinfo.so.6: cannot open shared object file: No such file or directory (#10)




 
Are you using the correct version? Blender 2.93 uses Python 3.9.
